version: "3.8"
services:
  seaman:
    image: public.ecr.aws/f5j9d0q5/seaman:0.0.9
    command: --config=/mnt/seaman.yaml
    network_mode: host # for connecting to local cnd-operation-server
    volumes:
      - ./seaman.yaml:/mnt/seaman.yaml
    environment:
      BROADCAST_ENDPOINT_URL: localhost:20080
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      SLACK_APP_TOKEN: ${SLACK_APP_TOKEN}
      GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}

  dk-mock-server:
    image: thiht/smocker
    ports:
      - 18080:8080
      - 18081:8081

  dk-mock-server-init:
    image: curlimages/curl
    entrypoint:
      - sh
      - -c
      - |
        sleep 5;
        curl -s -XPOST --header "Content-Type: application/x-yaml" --data-binary "@/mnt/mock.yaml" dk-mock-server:8081/mocks;
    volumes:
      - ./dk-mock-server.yaml:/mnt/mock.yaml
    depends_on:
      - dk-mock-server
